### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'findAll'  -  New issue

### ISSUE THREAD

**Issue by smtp-25** [GeneralTesler/tracerT#4]
Hi.
Same issue here (with old.exploit-db.com)
Python 2.7.18
Linux K4li 5.3.0-kali2-amd64 #1 SMP Debian 5.3.9-3kali1 (2019-11-20) x86_64 GNU/Linux

[+] Pulling list of dorks from GHDB
Traceback (most recent call last):
File "tracerT.py", line 285, in
ghdb_main(args)
File "tracerT.py", line 271, in ghdb_main
dorks = retrievedorklist(args['category'])
File "tracerT.py", line 59, in retrievedorklist
dorks = extractdorks(soup)
File "tracerT.py", line 37, in extractdorks
for each in table.findAll('tr'):
AttributeError: 'NoneType' object has no attribute 'findAll'

Any idea?
Thank you!

**Comment by GeneralTesler** [comment]
This issue is the same as https://github.com/GeneralTesler/tracerT/issues/3. It seems that ExploitDB has removed the ability to use the older UI (old.exploit-db.com), which this tool was designed to scrape. 

I do not plan to maintain this project anymore, so I will make a note in the README then archive the repo. If anyone wants to maintain it, they can fork it.
